#!/usr/bin/env bash

function print_out() {
    dig "$2.$1" | awk '/ANSWER SECTION:/{getline; printf("The subdomain %s is a %s record and points to %s\n", subDomain, $4, $5)}' subDomain="$SUBDOMAIN"
}
domain_arr=('www', 'lb-01', 'web-01', 'web-02')
if [[ -z '$2 ']]; then
    for sub_domain in '${domain_arr[@]}'; do
        print_out "$1" "$sub_domain"
    done
else
    for sub_domain in $2; do
        print_out "$1" "$sub_domain"
    done
fi
