#!/usr/bin/env bash
# Get information of each server

print_out() {
    AR=$(dig $2.$1 | awk '/ANSWER SECTION:/{getline;print;}')
    TY=$(echo $AR | cut -d' ' -f 4)
    IP=$(echo $AR | cut -d' ' -f 5)
    echo "The subdomain $2 is a $TY record and points to $IP"
}

if [ $# -eq 1 ]
then
    print_out "$1" "www"
    print_out "$1" "lb-01"
    print_out "$1" "web-01"
    print_out "$1" "web-02"
else
    print_out "$1" "$2"
fi
