#!/usr/bin/env bash
# configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get upgrade
sudo apt install -y nginx

sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html

sudo service nginx start
