#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

REDIRECT="\\\trewrite ^/redirect_me  https://www.youtube.com/watch?v=mCdA4bJAGGk permanet;"

sudo apt-get update -y 
sudo apt-get upgrade -y
sudo apt-get install -y nginx

sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart
