#!/usr/bin/env bash
# Nginx server config to have a custom 404 page that contains the string 
# 'Ceci n'est pas une page.'

apt-get update
apt-get install -y nginx

touch /var/www/example.com/html/index.html
echo "Hello World!" > /var/www/html/index.html

touch "/var/www/html/error_page.html"
echo "Ceci n'est pas une page" > /var/www/html/error_page.html

cp new_default /etc/nginx/sites-available/default

sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf

nginx -t
sudo /etc/init.d/nginx restart
