#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.

IP_address=$1
if [ -z "$IP_address" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$IP_address"
fi
