#!/usr/bin/env bash
# Script that print a message indefinitely and print another if try to finish it

term()
{
    echo "I am invicible!!!"
}

trap term SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done

