#!/usr/bin/env bash
# Script that print a message indefinitely and print another if try to finish it

trap "echo I am invincible!!!" SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
