#!/usr/bin/env bash
# display the tome for 12 houts and 59 minutes

hour=0
min=1
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $min -le 59 ]; do
        echo "$min"
        ((min++))
    done
    ((hour++))
    min=1
done
