#!/usr/bin/env bash
# script that give you information about school file

file="school"
if test -e "$file"; then
    echo "school file exists"
    if test ! -s "$file"; then
        echo "$file file is empty"
    elif test -s "$file"; then
        echo "school file is not empty"
    fi
    if test -f "$file"; then
        echo "school is a regular file"
    fi
else
    echo "$file file does not exist"
fi
