#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new

sed -i "/localhost/ s/.*/127.0.0.2\tlocalhost/g" ~/hosts.new
sed -i "/localhost/ a8.8.8.8\tfacebook.com" ~/hosts.new

cp -f ~/hosts.new /etc/hosts
