#!/usr/bin/env bash
# creates a RSA key pair
# - name if the created private key "school"
# - number of bits in the created key to be created "4096"
# - the created key is protected by the passphrase 'betty'

ssh-keygen -t rsa -f school -b 4096 -N betty 
